// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_msg_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_msg_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3019000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3019001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_msg_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_msg_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[5]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_msg_2eproto;
namespace test_2 {
class field_squence;
struct field_squenceDefaultTypeInternal;
extern field_squenceDefaultTypeInternal _field_squence_default_instance_;
class net_packet;
struct net_packetDefaultTypeInternal;
extern net_packetDefaultTypeInternal _net_packet_default_instance_;
class pair_value;
struct pair_valueDefaultTypeInternal;
extern pair_valueDefaultTypeInternal _pair_value_default_instance_;
class row_data;
struct row_dataDefaultTypeInternal;
extern row_dataDefaultTypeInternal _row_data_default_instance_;
class table_info;
struct table_infoDefaultTypeInternal;
extern table_infoDefaultTypeInternal _table_info_default_instance_;
}  // namespace test_2
PROTOBUF_NAMESPACE_OPEN
template<> ::test_2::field_squence* Arena::CreateMaybeMessage<::test_2::field_squence>(Arena*);
template<> ::test_2::net_packet* Arena::CreateMaybeMessage<::test_2::net_packet>(Arena*);
template<> ::test_2::pair_value* Arena::CreateMaybeMessage<::test_2::pair_value>(Arena*);
template<> ::test_2::row_data* Arena::CreateMaybeMessage<::test_2::row_data>(Arena*);
template<> ::test_2::table_info* Arena::CreateMaybeMessage<::test_2::table_info>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace test_2 {

enum DATA_TYPE : int {
  L_NUMBER = 0,
  L_STRING = 1,
  L_BOOL = 2,
  L_TABLE_STRING = 3,
  L_FUNCTION = 4,
  DATA_TYPE_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  DATA_TYPE_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool DATA_TYPE_IsValid(int value);
constexpr DATA_TYPE DATA_TYPE_MIN = L_NUMBER;
constexpr DATA_TYPE DATA_TYPE_MAX = L_FUNCTION;
constexpr int DATA_TYPE_ARRAYSIZE = DATA_TYPE_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* DATA_TYPE_descriptor();
template<typename T>
inline const std::string& DATA_TYPE_Name(T enum_t_value) {
  static_assert(::std::is_same<T, DATA_TYPE>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function DATA_TYPE_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    DATA_TYPE_descriptor(), enum_t_value);
}
inline bool DATA_TYPE_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, DATA_TYPE* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<DATA_TYPE>(
    DATA_TYPE_descriptor(), name, value);
}
// ===================================================================

class net_packet final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:test_2.net_packet) */ {
 public:
  inline net_packet() : net_packet(nullptr) {}
  ~net_packet() override;
  explicit constexpr net_packet(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  net_packet(const net_packet& from);
  net_packet(net_packet&& from) noexcept
    : net_packet() {
    *this = ::std::move(from);
  }

  inline net_packet& operator=(const net_packet& from) {
    CopyFrom(from);
    return *this;
  }
  inline net_packet& operator=(net_packet&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const net_packet& default_instance() {
    return *internal_default_instance();
  }
  static inline const net_packet* internal_default_instance() {
    return reinterpret_cast<const net_packet*>(
               &_net_packet_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(net_packet& a, net_packet& b) {
    a.Swap(&b);
  }
  inline void Swap(net_packet* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(net_packet* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  net_packet* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<net_packet>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const net_packet& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const net_packet& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(net_packet* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "test_2.net_packet";
  }
  protected:
  explicit net_packet(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kDataFieldNumber = 3,
    kSystemFieldNumber = 1,
    kCmdFieldNumber = 2,
  };
  // string data = 3;
  void clear_data();
  const std::string& data() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_data(ArgT0&& arg0, ArgT... args);
  std::string* mutable_data();
  PROTOBUF_NODISCARD std::string* release_data();
  void set_allocated_data(std::string* data);
  private:
  const std::string& _internal_data() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_data(const std::string& value);
  std::string* _internal_mutable_data();
  public:

  // int32 system = 1;
  void clear_system();
  int32_t system() const;
  void set_system(int32_t value);
  private:
  int32_t _internal_system() const;
  void _internal_set_system(int32_t value);
  public:

  // int32 cmd = 2;
  void clear_cmd();
  int32_t cmd() const;
  void set_cmd(int32_t value);
  private:
  int32_t _internal_cmd() const;
  void _internal_set_cmd(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:test_2.net_packet)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr data_;
  int32_t system_;
  int32_t cmd_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_msg_2eproto;
};
// -------------------------------------------------------------------

class pair_value final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:test_2.pair_value) */ {
 public:
  inline pair_value() : pair_value(nullptr) {}
  ~pair_value() override;
  explicit constexpr pair_value(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  pair_value(const pair_value& from);
  pair_value(pair_value&& from) noexcept
    : pair_value() {
    *this = ::std::move(from);
  }

  inline pair_value& operator=(const pair_value& from) {
    CopyFrom(from);
    return *this;
  }
  inline pair_value& operator=(pair_value&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const pair_value& default_instance() {
    return *internal_default_instance();
  }
  static inline const pair_value* internal_default_instance() {
    return reinterpret_cast<const pair_value*>(
               &_pair_value_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(pair_value& a, pair_value& b) {
    a.Swap(&b);
  }
  inline void Swap(pair_value* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(pair_value* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  pair_value* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<pair_value>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const pair_value& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const pair_value& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(pair_value* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "test_2.pair_value";
  }
  protected:
  explicit pair_value(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kKeyFieldNumber = 1,
    kValueFieldNumber = 2,
  };
  // string key = 1;
  void clear_key();
  const std::string& key() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_key(ArgT0&& arg0, ArgT... args);
  std::string* mutable_key();
  PROTOBUF_NODISCARD std::string* release_key();
  void set_allocated_key(std::string* key);
  private:
  const std::string& _internal_key() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_key(const std::string& value);
  std::string* _internal_mutable_key();
  public:

  // string value = 2;
  void clear_value();
  const std::string& value() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_value(ArgT0&& arg0, ArgT... args);
  std::string* mutable_value();
  PROTOBUF_NODISCARD std::string* release_value();
  void set_allocated_value(std::string* value);
  private:
  const std::string& _internal_value() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_value(const std::string& value);
  std::string* _internal_mutable_value();
  public:

  // @@protoc_insertion_point(class_scope:test_2.pair_value)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr key_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr value_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_msg_2eproto;
};
// -------------------------------------------------------------------

class row_data final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:test_2.row_data) */ {
 public:
  inline row_data() : row_data(nullptr) {}
  ~row_data() override;
  explicit constexpr row_data(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  row_data(const row_data& from);
  row_data(row_data&& from) noexcept
    : row_data() {
    *this = ::std::move(from);
  }

  inline row_data& operator=(const row_data& from) {
    CopyFrom(from);
    return *this;
  }
  inline row_data& operator=(row_data&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const row_data& default_instance() {
    return *internal_default_instance();
  }
  static inline const row_data* internal_default_instance() {
    return reinterpret_cast<const row_data*>(
               &_row_data_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(row_data& a, row_data& b) {
    a.Swap(&b);
  }
  inline void Swap(row_data* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(row_data* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  row_data* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<row_data>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const row_data& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const row_data& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(row_data* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "test_2.row_data";
  }
  protected:
  explicit row_data(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPairFieldNumber = 2,
    kKeyFieldNumber = 1,
  };
  // repeated .test_2.pair_value pair = 2;
  int pair_size() const;
  private:
  int _internal_pair_size() const;
  public:
  void clear_pair();
  ::test_2::pair_value* mutable_pair(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::test_2::pair_value >*
      mutable_pair();
  private:
  const ::test_2::pair_value& _internal_pair(int index) const;
  ::test_2::pair_value* _internal_add_pair();
  public:
  const ::test_2::pair_value& pair(int index) const;
  ::test_2::pair_value* add_pair();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::test_2::pair_value >&
      pair() const;

  // string key = 1;
  void clear_key();
  const std::string& key() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_key(ArgT0&& arg0, ArgT... args);
  std::string* mutable_key();
  PROTOBUF_NODISCARD std::string* release_key();
  void set_allocated_key(std::string* key);
  private:
  const std::string& _internal_key() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_key(const std::string& value);
  std::string* _internal_mutable_key();
  public:

  // @@protoc_insertion_point(class_scope:test_2.row_data)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::test_2::pair_value > pair_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr key_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_msg_2eproto;
};
// -------------------------------------------------------------------

class field_squence final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:test_2.field_squence) */ {
 public:
  inline field_squence() : field_squence(nullptr) {}
  ~field_squence() override;
  explicit constexpr field_squence(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  field_squence(const field_squence& from);
  field_squence(field_squence&& from) noexcept
    : field_squence() {
    *this = ::std::move(from);
  }

  inline field_squence& operator=(const field_squence& from) {
    CopyFrom(from);
    return *this;
  }
  inline field_squence& operator=(field_squence&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const field_squence& default_instance() {
    return *internal_default_instance();
  }
  static inline const field_squence* internal_default_instance() {
    return reinterpret_cast<const field_squence*>(
               &_field_squence_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(field_squence& a, field_squence& b) {
    a.Swap(&b);
  }
  inline void Swap(field_squence* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(field_squence* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  field_squence* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<field_squence>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const field_squence& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const field_squence& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(field_squence* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "test_2.field_squence";
  }
  protected:
  explicit field_squence(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kLevelsFieldNumber = 1,
    kFieldFieldNumber = 2,
    kFiledTypesFieldNumber = 3,
  };
  // repeated int32 levels = 1;
  int levels_size() const;
  private:
  int _internal_levels_size() const;
  public:
  void clear_levels();
  private:
  int32_t _internal_levels(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
      _internal_levels() const;
  void _internal_add_levels(int32_t value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
      _internal_mutable_levels();
  public:
  int32_t levels(int index) const;
  void set_levels(int index, int32_t value);
  void add_levels(int32_t value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
      levels() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
      mutable_levels();

  // repeated string field = 2;
  int field_size() const;
  private:
  int _internal_field_size() const;
  public:
  void clear_field();
  const std::string& field(int index) const;
  std::string* mutable_field(int index);
  void set_field(int index, const std::string& value);
  void set_field(int index, std::string&& value);
  void set_field(int index, const char* value);
  void set_field(int index, const char* value, size_t size);
  std::string* add_field();
  void add_field(const std::string& value);
  void add_field(std::string&& value);
  void add_field(const char* value);
  void add_field(const char* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& field() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_field();
  private:
  const std::string& _internal_field(int index) const;
  std::string* _internal_add_field();
  public:

  // repeated string filed_types = 3;
  int filed_types_size() const;
  private:
  int _internal_filed_types_size() const;
  public:
  void clear_filed_types();
  const std::string& filed_types(int index) const;
  std::string* mutable_filed_types(int index);
  void set_filed_types(int index, const std::string& value);
  void set_filed_types(int index, std::string&& value);
  void set_filed_types(int index, const char* value);
  void set_filed_types(int index, const char* value, size_t size);
  std::string* add_filed_types();
  void add_filed_types(const std::string& value);
  void add_filed_types(std::string&& value);
  void add_filed_types(const char* value);
  void add_filed_types(const char* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& filed_types() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_filed_types();
  private:
  const std::string& _internal_filed_types(int index) const;
  std::string* _internal_add_filed_types();
  public:

  // @@protoc_insertion_point(class_scope:test_2.field_squence)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t > levels_;
  mutable std::atomic<int> _levels_cached_byte_size_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> field_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> filed_types_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_msg_2eproto;
};
// -------------------------------------------------------------------

class table_info final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:test_2.table_info) */ {
 public:
  inline table_info() : table_info(nullptr) {}
  ~table_info() override;
  explicit constexpr table_info(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  table_info(const table_info& from);
  table_info(table_info&& from) noexcept
    : table_info() {
    *this = ::std::move(from);
  }

  inline table_info& operator=(const table_info& from) {
    CopyFrom(from);
    return *this;
  }
  inline table_info& operator=(table_info&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const table_info& default_instance() {
    return *internal_default_instance();
  }
  static inline const table_info* internal_default_instance() {
    return reinterpret_cast<const table_info*>(
               &_table_info_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(table_info& a, table_info& b) {
    a.Swap(&b);
  }
  inline void Swap(table_info* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(table_info* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  table_info* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<table_info>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const table_info& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const table_info& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(table_info* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "test_2.table_info";
  }
  protected:
  explicit table_info(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kFiledNamesFieldNumber = 4,
    kFiledTypesFieldNumber = 5,
    kFiledSequencesFieldNumber = 6,
    kRowListsFieldNumber = 7,
    kTableNameFieldNumber = 1,
    kRowCountFieldNumber = 2,
    kColumnCountFieldNumber = 3,
  };
  // repeated string filed_names = 4;
  int filed_names_size() const;
  private:
  int _internal_filed_names_size() const;
  public:
  void clear_filed_names();
  const std::string& filed_names(int index) const;
  std::string* mutable_filed_names(int index);
  void set_filed_names(int index, const std::string& value);
  void set_filed_names(int index, std::string&& value);
  void set_filed_names(int index, const char* value);
  void set_filed_names(int index, const char* value, size_t size);
  std::string* add_filed_names();
  void add_filed_names(const std::string& value);
  void add_filed_names(std::string&& value);
  void add_filed_names(const char* value);
  void add_filed_names(const char* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& filed_names() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_filed_names();
  private:
  const std::string& _internal_filed_names(int index) const;
  std::string* _internal_add_filed_names();
  public:

  // repeated string filed_types = 5;
  int filed_types_size() const;
  private:
  int _internal_filed_types_size() const;
  public:
  void clear_filed_types();
  const std::string& filed_types(int index) const;
  std::string* mutable_filed_types(int index);
  void set_filed_types(int index, const std::string& value);
  void set_filed_types(int index, std::string&& value);
  void set_filed_types(int index, const char* value);
  void set_filed_types(int index, const char* value, size_t size);
  std::string* add_filed_types();
  void add_filed_types(const std::string& value);
  void add_filed_types(std::string&& value);
  void add_filed_types(const char* value);
  void add_filed_types(const char* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& filed_types() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_filed_types();
  private:
  const std::string& _internal_filed_types(int index) const;
  std::string* _internal_add_filed_types();
  public:

  // repeated .test_2.field_squence filed_sequences = 6;
  int filed_sequences_size() const;
  private:
  int _internal_filed_sequences_size() const;
  public:
  void clear_filed_sequences();
  ::test_2::field_squence* mutable_filed_sequences(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::test_2::field_squence >*
      mutable_filed_sequences();
  private:
  const ::test_2::field_squence& _internal_filed_sequences(int index) const;
  ::test_2::field_squence* _internal_add_filed_sequences();
  public:
  const ::test_2::field_squence& filed_sequences(int index) const;
  ::test_2::field_squence* add_filed_sequences();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::test_2::field_squence >&
      filed_sequences() const;

  // repeated .test_2.row_data row_lists = 7;
  int row_lists_size() const;
  private:
  int _internal_row_lists_size() const;
  public:
  void clear_row_lists();
  ::test_2::row_data* mutable_row_lists(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::test_2::row_data >*
      mutable_row_lists();
  private:
  const ::test_2::row_data& _internal_row_lists(int index) const;
  ::test_2::row_data* _internal_add_row_lists();
  public:
  const ::test_2::row_data& row_lists(int index) const;
  ::test_2::row_data* add_row_lists();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::test_2::row_data >&
      row_lists() const;

  // string table_name = 1;
  void clear_table_name();
  const std::string& table_name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_table_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_table_name();
  PROTOBUF_NODISCARD std::string* release_table_name();
  void set_allocated_table_name(std::string* table_name);
  private:
  const std::string& _internal_table_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_table_name(const std::string& value);
  std::string* _internal_mutable_table_name();
  public:

  // int32 row_count = 2;
  void clear_row_count();
  int32_t row_count() const;
  void set_row_count(int32_t value);
  private:
  int32_t _internal_row_count() const;
  void _internal_set_row_count(int32_t value);
  public:

  // int32 column_count = 3;
  void clear_column_count();
  int32_t column_count() const;
  void set_column_count(int32_t value);
  private:
  int32_t _internal_column_count() const;
  void _internal_set_column_count(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:test_2.table_info)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> filed_names_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> filed_types_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::test_2::field_squence > filed_sequences_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::test_2::row_data > row_lists_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr table_name_;
  int32_t row_count_;
  int32_t column_count_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_msg_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// net_packet

// int32 system = 1;
inline void net_packet::clear_system() {
  system_ = 0;
}
inline int32_t net_packet::_internal_system() const {
  return system_;
}
inline int32_t net_packet::system() const {
  // @@protoc_insertion_point(field_get:test_2.net_packet.system)
  return _internal_system();
}
inline void net_packet::_internal_set_system(int32_t value) {
  
  system_ = value;
}
inline void net_packet::set_system(int32_t value) {
  _internal_set_system(value);
  // @@protoc_insertion_point(field_set:test_2.net_packet.system)
}

// int32 cmd = 2;
inline void net_packet::clear_cmd() {
  cmd_ = 0;
}
inline int32_t net_packet::_internal_cmd() const {
  return cmd_;
}
inline int32_t net_packet::cmd() const {
  // @@protoc_insertion_point(field_get:test_2.net_packet.cmd)
  return _internal_cmd();
}
inline void net_packet::_internal_set_cmd(int32_t value) {
  
  cmd_ = value;
}
inline void net_packet::set_cmd(int32_t value) {
  _internal_set_cmd(value);
  // @@protoc_insertion_point(field_set:test_2.net_packet.cmd)
}

// string data = 3;
inline void net_packet::clear_data() {
  data_.ClearToEmpty();
}
inline const std::string& net_packet::data() const {
  // @@protoc_insertion_point(field_get:test_2.net_packet.data)
  return _internal_data();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void net_packet::set_data(ArgT0&& arg0, ArgT... args) {
 
 data_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:test_2.net_packet.data)
}
inline std::string* net_packet::mutable_data() {
  std::string* _s = _internal_mutable_data();
  // @@protoc_insertion_point(field_mutable:test_2.net_packet.data)
  return _s;
}
inline const std::string& net_packet::_internal_data() const {
  return data_.Get();
}
inline void net_packet::_internal_set_data(const std::string& value) {
  
  data_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* net_packet::_internal_mutable_data() {
  
  return data_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* net_packet::release_data() {
  // @@protoc_insertion_point(field_release:test_2.net_packet.data)
  return data_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void net_packet::set_allocated_data(std::string* data) {
  if (data != nullptr) {
    
  } else {
    
  }
  data_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), data,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (data_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    data_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:test_2.net_packet.data)
}

// -------------------------------------------------------------------

// pair_value

// string key = 1;
inline void pair_value::clear_key() {
  key_.ClearToEmpty();
}
inline const std::string& pair_value::key() const {
  // @@protoc_insertion_point(field_get:test_2.pair_value.key)
  return _internal_key();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void pair_value::set_key(ArgT0&& arg0, ArgT... args) {
 
 key_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:test_2.pair_value.key)
}
inline std::string* pair_value::mutable_key() {
  std::string* _s = _internal_mutable_key();
  // @@protoc_insertion_point(field_mutable:test_2.pair_value.key)
  return _s;
}
inline const std::string& pair_value::_internal_key() const {
  return key_.Get();
}
inline void pair_value::_internal_set_key(const std::string& value) {
  
  key_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* pair_value::_internal_mutable_key() {
  
  return key_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* pair_value::release_key() {
  // @@protoc_insertion_point(field_release:test_2.pair_value.key)
  return key_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void pair_value::set_allocated_key(std::string* key) {
  if (key != nullptr) {
    
  } else {
    
  }
  key_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), key,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (key_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    key_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:test_2.pair_value.key)
}

// string value = 2;
inline void pair_value::clear_value() {
  value_.ClearToEmpty();
}
inline const std::string& pair_value::value() const {
  // @@protoc_insertion_point(field_get:test_2.pair_value.value)
  return _internal_value();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void pair_value::set_value(ArgT0&& arg0, ArgT... args) {
 
 value_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:test_2.pair_value.value)
}
inline std::string* pair_value::mutable_value() {
  std::string* _s = _internal_mutable_value();
  // @@protoc_insertion_point(field_mutable:test_2.pair_value.value)
  return _s;
}
inline const std::string& pair_value::_internal_value() const {
  return value_.Get();
}
inline void pair_value::_internal_set_value(const std::string& value) {
  
  value_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* pair_value::_internal_mutable_value() {
  
  return value_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* pair_value::release_value() {
  // @@protoc_insertion_point(field_release:test_2.pair_value.value)
  return value_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void pair_value::set_allocated_value(std::string* value) {
  if (value != nullptr) {
    
  } else {
    
  }
  value_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (value_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    value_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:test_2.pair_value.value)
}

// -------------------------------------------------------------------

// row_data

// string key = 1;
inline void row_data::clear_key() {
  key_.ClearToEmpty();
}
inline const std::string& row_data::key() const {
  // @@protoc_insertion_point(field_get:test_2.row_data.key)
  return _internal_key();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void row_data::set_key(ArgT0&& arg0, ArgT... args) {
 
 key_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:test_2.row_data.key)
}
inline std::string* row_data::mutable_key() {
  std::string* _s = _internal_mutable_key();
  // @@protoc_insertion_point(field_mutable:test_2.row_data.key)
  return _s;
}
inline const std::string& row_data::_internal_key() const {
  return key_.Get();
}
inline void row_data::_internal_set_key(const std::string& value) {
  
  key_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* row_data::_internal_mutable_key() {
  
  return key_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* row_data::release_key() {
  // @@protoc_insertion_point(field_release:test_2.row_data.key)
  return key_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void row_data::set_allocated_key(std::string* key) {
  if (key != nullptr) {
    
  } else {
    
  }
  key_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), key,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (key_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    key_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:test_2.row_data.key)
}

// repeated .test_2.pair_value pair = 2;
inline int row_data::_internal_pair_size() const {
  return pair_.size();
}
inline int row_data::pair_size() const {
  return _internal_pair_size();
}
inline void row_data::clear_pair() {
  pair_.Clear();
}
inline ::test_2::pair_value* row_data::mutable_pair(int index) {
  // @@protoc_insertion_point(field_mutable:test_2.row_data.pair)
  return pair_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::test_2::pair_value >*
row_data::mutable_pair() {
  // @@protoc_insertion_point(field_mutable_list:test_2.row_data.pair)
  return &pair_;
}
inline const ::test_2::pair_value& row_data::_internal_pair(int index) const {
  return pair_.Get(index);
}
inline const ::test_2::pair_value& row_data::pair(int index) const {
  // @@protoc_insertion_point(field_get:test_2.row_data.pair)
  return _internal_pair(index);
}
inline ::test_2::pair_value* row_data::_internal_add_pair() {
  return pair_.Add();
}
inline ::test_2::pair_value* row_data::add_pair() {
  ::test_2::pair_value* _add = _internal_add_pair();
  // @@protoc_insertion_point(field_add:test_2.row_data.pair)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::test_2::pair_value >&
row_data::pair() const {
  // @@protoc_insertion_point(field_list:test_2.row_data.pair)
  return pair_;
}

// -------------------------------------------------------------------

// field_squence

// repeated int32 levels = 1;
inline int field_squence::_internal_levels_size() const {
  return levels_.size();
}
inline int field_squence::levels_size() const {
  return _internal_levels_size();
}
inline void field_squence::clear_levels() {
  levels_.Clear();
}
inline int32_t field_squence::_internal_levels(int index) const {
  return levels_.Get(index);
}
inline int32_t field_squence::levels(int index) const {
  // @@protoc_insertion_point(field_get:test_2.field_squence.levels)
  return _internal_levels(index);
}
inline void field_squence::set_levels(int index, int32_t value) {
  levels_.Set(index, value);
  // @@protoc_insertion_point(field_set:test_2.field_squence.levels)
}
inline void field_squence::_internal_add_levels(int32_t value) {
  levels_.Add(value);
}
inline void field_squence::add_levels(int32_t value) {
  _internal_add_levels(value);
  // @@protoc_insertion_point(field_add:test_2.field_squence.levels)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
field_squence::_internal_levels() const {
  return levels_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
field_squence::levels() const {
  // @@protoc_insertion_point(field_list:test_2.field_squence.levels)
  return _internal_levels();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
field_squence::_internal_mutable_levels() {
  return &levels_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
field_squence::mutable_levels() {
  // @@protoc_insertion_point(field_mutable_list:test_2.field_squence.levels)
  return _internal_mutable_levels();
}

// repeated string field = 2;
inline int field_squence::_internal_field_size() const {
  return field_.size();
}
inline int field_squence::field_size() const {
  return _internal_field_size();
}
inline void field_squence::clear_field() {
  field_.Clear();
}
inline std::string* field_squence::add_field() {
  std::string* _s = _internal_add_field();
  // @@protoc_insertion_point(field_add_mutable:test_2.field_squence.field)
  return _s;
}
inline const std::string& field_squence::_internal_field(int index) const {
  return field_.Get(index);
}
inline const std::string& field_squence::field(int index) const {
  // @@protoc_insertion_point(field_get:test_2.field_squence.field)
  return _internal_field(index);
}
inline std::string* field_squence::mutable_field(int index) {
  // @@protoc_insertion_point(field_mutable:test_2.field_squence.field)
  return field_.Mutable(index);
}
inline void field_squence::set_field(int index, const std::string& value) {
  field_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set:test_2.field_squence.field)
}
inline void field_squence::set_field(int index, std::string&& value) {
  field_.Mutable(index)->assign(std::move(value));
  // @@protoc_insertion_point(field_set:test_2.field_squence.field)
}
inline void field_squence::set_field(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  field_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:test_2.field_squence.field)
}
inline void field_squence::set_field(int index, const char* value, size_t size) {
  field_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:test_2.field_squence.field)
}
inline std::string* field_squence::_internal_add_field() {
  return field_.Add();
}
inline void field_squence::add_field(const std::string& value) {
  field_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:test_2.field_squence.field)
}
inline void field_squence::add_field(std::string&& value) {
  field_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:test_2.field_squence.field)
}
inline void field_squence::add_field(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  field_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:test_2.field_squence.field)
}
inline void field_squence::add_field(const char* value, size_t size) {
  field_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:test_2.field_squence.field)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
field_squence::field() const {
  // @@protoc_insertion_point(field_list:test_2.field_squence.field)
  return field_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
field_squence::mutable_field() {
  // @@protoc_insertion_point(field_mutable_list:test_2.field_squence.field)
  return &field_;
}

// repeated string filed_types = 3;
inline int field_squence::_internal_filed_types_size() const {
  return filed_types_.size();
}
inline int field_squence::filed_types_size() const {
  return _internal_filed_types_size();
}
inline void field_squence::clear_filed_types() {
  filed_types_.Clear();
}
inline std::string* field_squence::add_filed_types() {
  std::string* _s = _internal_add_filed_types();
  // @@protoc_insertion_point(field_add_mutable:test_2.field_squence.filed_types)
  return _s;
}
inline const std::string& field_squence::_internal_filed_types(int index) const {
  return filed_types_.Get(index);
}
inline const std::string& field_squence::filed_types(int index) const {
  // @@protoc_insertion_point(field_get:test_2.field_squence.filed_types)
  return _internal_filed_types(index);
}
inline std::string* field_squence::mutable_filed_types(int index) {
  // @@protoc_insertion_point(field_mutable:test_2.field_squence.filed_types)
  return filed_types_.Mutable(index);
}
inline void field_squence::set_filed_types(int index, const std::string& value) {
  filed_types_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set:test_2.field_squence.filed_types)
}
inline void field_squence::set_filed_types(int index, std::string&& value) {
  filed_types_.Mutable(index)->assign(std::move(value));
  // @@protoc_insertion_point(field_set:test_2.field_squence.filed_types)
}
inline void field_squence::set_filed_types(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  filed_types_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:test_2.field_squence.filed_types)
}
inline void field_squence::set_filed_types(int index, const char* value, size_t size) {
  filed_types_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:test_2.field_squence.filed_types)
}
inline std::string* field_squence::_internal_add_filed_types() {
  return filed_types_.Add();
}
inline void field_squence::add_filed_types(const std::string& value) {
  filed_types_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:test_2.field_squence.filed_types)
}
inline void field_squence::add_filed_types(std::string&& value) {
  filed_types_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:test_2.field_squence.filed_types)
}
inline void field_squence::add_filed_types(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  filed_types_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:test_2.field_squence.filed_types)
}
inline void field_squence::add_filed_types(const char* value, size_t size) {
  filed_types_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:test_2.field_squence.filed_types)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
field_squence::filed_types() const {
  // @@protoc_insertion_point(field_list:test_2.field_squence.filed_types)
  return filed_types_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
field_squence::mutable_filed_types() {
  // @@protoc_insertion_point(field_mutable_list:test_2.field_squence.filed_types)
  return &filed_types_;
}

// -------------------------------------------------------------------

// table_info

// string table_name = 1;
inline void table_info::clear_table_name() {
  table_name_.ClearToEmpty();
}
inline const std::string& table_info::table_name() const {
  // @@protoc_insertion_point(field_get:test_2.table_info.table_name)
  return _internal_table_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void table_info::set_table_name(ArgT0&& arg0, ArgT... args) {
 
 table_name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:test_2.table_info.table_name)
}
inline std::string* table_info::mutable_table_name() {
  std::string* _s = _internal_mutable_table_name();
  // @@protoc_insertion_point(field_mutable:test_2.table_info.table_name)
  return _s;
}
inline const std::string& table_info::_internal_table_name() const {
  return table_name_.Get();
}
inline void table_info::_internal_set_table_name(const std::string& value) {
  
  table_name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* table_info::_internal_mutable_table_name() {
  
  return table_name_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* table_info::release_table_name() {
  // @@protoc_insertion_point(field_release:test_2.table_info.table_name)
  return table_name_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void table_info::set_allocated_table_name(std::string* table_name) {
  if (table_name != nullptr) {
    
  } else {
    
  }
  table_name_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), table_name,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (table_name_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    table_name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:test_2.table_info.table_name)
}

// int32 row_count = 2;
inline void table_info::clear_row_count() {
  row_count_ = 0;
}
inline int32_t table_info::_internal_row_count() const {
  return row_count_;
}
inline int32_t table_info::row_count() const {
  // @@protoc_insertion_point(field_get:test_2.table_info.row_count)
  return _internal_row_count();
}
inline void table_info::_internal_set_row_count(int32_t value) {
  
  row_count_ = value;
}
inline void table_info::set_row_count(int32_t value) {
  _internal_set_row_count(value);
  // @@protoc_insertion_point(field_set:test_2.table_info.row_count)
}

// int32 column_count = 3;
inline void table_info::clear_column_count() {
  column_count_ = 0;
}
inline int32_t table_info::_internal_column_count() const {
  return column_count_;
}
inline int32_t table_info::column_count() const {
  // @@protoc_insertion_point(field_get:test_2.table_info.column_count)
  return _internal_column_count();
}
inline void table_info::_internal_set_column_count(int32_t value) {
  
  column_count_ = value;
}
inline void table_info::set_column_count(int32_t value) {
  _internal_set_column_count(value);
  // @@protoc_insertion_point(field_set:test_2.table_info.column_count)
}

// repeated string filed_names = 4;
inline int table_info::_internal_filed_names_size() const {
  return filed_names_.size();
}
inline int table_info::filed_names_size() const {
  return _internal_filed_names_size();
}
inline void table_info::clear_filed_names() {
  filed_names_.Clear();
}
inline std::string* table_info::add_filed_names() {
  std::string* _s = _internal_add_filed_names();
  // @@protoc_insertion_point(field_add_mutable:test_2.table_info.filed_names)
  return _s;
}
inline const std::string& table_info::_internal_filed_names(int index) const {
  return filed_names_.Get(index);
}
inline const std::string& table_info::filed_names(int index) const {
  // @@protoc_insertion_point(field_get:test_2.table_info.filed_names)
  return _internal_filed_names(index);
}
inline std::string* table_info::mutable_filed_names(int index) {
  // @@protoc_insertion_point(field_mutable:test_2.table_info.filed_names)
  return filed_names_.Mutable(index);
}
inline void table_info::set_filed_names(int index, const std::string& value) {
  filed_names_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set:test_2.table_info.filed_names)
}
inline void table_info::set_filed_names(int index, std::string&& value) {
  filed_names_.Mutable(index)->assign(std::move(value));
  // @@protoc_insertion_point(field_set:test_2.table_info.filed_names)
}
inline void table_info::set_filed_names(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  filed_names_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:test_2.table_info.filed_names)
}
inline void table_info::set_filed_names(int index, const char* value, size_t size) {
  filed_names_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:test_2.table_info.filed_names)
}
inline std::string* table_info::_internal_add_filed_names() {
  return filed_names_.Add();
}
inline void table_info::add_filed_names(const std::string& value) {
  filed_names_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:test_2.table_info.filed_names)
}
inline void table_info::add_filed_names(std::string&& value) {
  filed_names_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:test_2.table_info.filed_names)
}
inline void table_info::add_filed_names(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  filed_names_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:test_2.table_info.filed_names)
}
inline void table_info::add_filed_names(const char* value, size_t size) {
  filed_names_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:test_2.table_info.filed_names)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
table_info::filed_names() const {
  // @@protoc_insertion_point(field_list:test_2.table_info.filed_names)
  return filed_names_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
table_info::mutable_filed_names() {
  // @@protoc_insertion_point(field_mutable_list:test_2.table_info.filed_names)
  return &filed_names_;
}

// repeated string filed_types = 5;
inline int table_info::_internal_filed_types_size() const {
  return filed_types_.size();
}
inline int table_info::filed_types_size() const {
  return _internal_filed_types_size();
}
inline void table_info::clear_filed_types() {
  filed_types_.Clear();
}
inline std::string* table_info::add_filed_types() {
  std::string* _s = _internal_add_filed_types();
  // @@protoc_insertion_point(field_add_mutable:test_2.table_info.filed_types)
  return _s;
}
inline const std::string& table_info::_internal_filed_types(int index) const {
  return filed_types_.Get(index);
}
inline const std::string& table_info::filed_types(int index) const {
  // @@protoc_insertion_point(field_get:test_2.table_info.filed_types)
  return _internal_filed_types(index);
}
inline std::string* table_info::mutable_filed_types(int index) {
  // @@protoc_insertion_point(field_mutable:test_2.table_info.filed_types)
  return filed_types_.Mutable(index);
}
inline void table_info::set_filed_types(int index, const std::string& value) {
  filed_types_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set:test_2.table_info.filed_types)
}
inline void table_info::set_filed_types(int index, std::string&& value) {
  filed_types_.Mutable(index)->assign(std::move(value));
  // @@protoc_insertion_point(field_set:test_2.table_info.filed_types)
}
inline void table_info::set_filed_types(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  filed_types_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:test_2.table_info.filed_types)
}
inline void table_info::set_filed_types(int index, const char* value, size_t size) {
  filed_types_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:test_2.table_info.filed_types)
}
inline std::string* table_info::_internal_add_filed_types() {
  return filed_types_.Add();
}
inline void table_info::add_filed_types(const std::string& value) {
  filed_types_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:test_2.table_info.filed_types)
}
inline void table_info::add_filed_types(std::string&& value) {
  filed_types_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:test_2.table_info.filed_types)
}
inline void table_info::add_filed_types(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  filed_types_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:test_2.table_info.filed_types)
}
inline void table_info::add_filed_types(const char* value, size_t size) {
  filed_types_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:test_2.table_info.filed_types)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
table_info::filed_types() const {
  // @@protoc_insertion_point(field_list:test_2.table_info.filed_types)
  return filed_types_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
table_info::mutable_filed_types() {
  // @@protoc_insertion_point(field_mutable_list:test_2.table_info.filed_types)
  return &filed_types_;
}

// repeated .test_2.field_squence filed_sequences = 6;
inline int table_info::_internal_filed_sequences_size() const {
  return filed_sequences_.size();
}
inline int table_info::filed_sequences_size() const {
  return _internal_filed_sequences_size();
}
inline void table_info::clear_filed_sequences() {
  filed_sequences_.Clear();
}
inline ::test_2::field_squence* table_info::mutable_filed_sequences(int index) {
  // @@protoc_insertion_point(field_mutable:test_2.table_info.filed_sequences)
  return filed_sequences_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::test_2::field_squence >*
table_info::mutable_filed_sequences() {
  // @@protoc_insertion_point(field_mutable_list:test_2.table_info.filed_sequences)
  return &filed_sequences_;
}
inline const ::test_2::field_squence& table_info::_internal_filed_sequences(int index) const {
  return filed_sequences_.Get(index);
}
inline const ::test_2::field_squence& table_info::filed_sequences(int index) const {
  // @@protoc_insertion_point(field_get:test_2.table_info.filed_sequences)
  return _internal_filed_sequences(index);
}
inline ::test_2::field_squence* table_info::_internal_add_filed_sequences() {
  return filed_sequences_.Add();
}
inline ::test_2::field_squence* table_info::add_filed_sequences() {
  ::test_2::field_squence* _add = _internal_add_filed_sequences();
  // @@protoc_insertion_point(field_add:test_2.table_info.filed_sequences)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::test_2::field_squence >&
table_info::filed_sequences() const {
  // @@protoc_insertion_point(field_list:test_2.table_info.filed_sequences)
  return filed_sequences_;
}

// repeated .test_2.row_data row_lists = 7;
inline int table_info::_internal_row_lists_size() const {
  return row_lists_.size();
}
inline int table_info::row_lists_size() const {
  return _internal_row_lists_size();
}
inline void table_info::clear_row_lists() {
  row_lists_.Clear();
}
inline ::test_2::row_data* table_info::mutable_row_lists(int index) {
  // @@protoc_insertion_point(field_mutable:test_2.table_info.row_lists)
  return row_lists_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::test_2::row_data >*
table_info::mutable_row_lists() {
  // @@protoc_insertion_point(field_mutable_list:test_2.table_info.row_lists)
  return &row_lists_;
}
inline const ::test_2::row_data& table_info::_internal_row_lists(int index) const {
  return row_lists_.Get(index);
}
inline const ::test_2::row_data& table_info::row_lists(int index) const {
  // @@protoc_insertion_point(field_get:test_2.table_info.row_lists)
  return _internal_row_lists(index);
}
inline ::test_2::row_data* table_info::_internal_add_row_lists() {
  return row_lists_.Add();
}
inline ::test_2::row_data* table_info::add_row_lists() {
  ::test_2::row_data* _add = _internal_add_row_lists();
  // @@protoc_insertion_point(field_add:test_2.table_info.row_lists)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::test_2::row_data >&
table_info::row_lists() const {
  // @@protoc_insertion_point(field_list:test_2.table_info.row_lists)
  return row_lists_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace test_2

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::test_2::DATA_TYPE> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::test_2::DATA_TYPE>() {
  return ::test_2::DATA_TYPE_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_msg_2eproto
